### ISSUE TITLE
How to handle `from . import *`

### ISSUE THREAD

**Issue by CJ-Wright** [symbol-management/symbol-exporter#109]
This doesn't have a `shadows` which is causing errors in runs.

**Comment by CJ-Wright-Citadel** [comment]
What do you think @dacamo76

**Comment by dacamo76** [comment]
How does it fail?
Our runs shouldn't fail if there is no "shadows" on a relative star import, our data model does not define "shadows" for relative star imports. (nor for regular star imports)

We decided, for our sanity, not to expand relative star imports, we can look into adding it though.

Thinking out load here 🤔.

"shadows" was meant to convey that a symbol was renamed in the current namespace.
If in 'my_module.py' we have the following:
```python
from numpy import ones
```
then we say surface area symbol `my_module.ones` "shadows" `numpy.ones`

For a star import there is no concept of "shadows"
```python
from .numpy import *
```
now we have a bunch of symbols slammed into the surface but we don't know what they are, so we aren't sure what they shadow so we just punt and say, "hey, you are importing numpy.* into your symbol space, good luck."

So we come to the special case of relative star imports:
In 'my_module.py'
```python
from .module2 import *
```

and in 'module2.py'
```python
def abs():
    pass
```

If we assume all relative imports are in the package (let's ignore [namespace packages](https://www.python.org/dev/peps/pep-0420/#differences-between-namespace-packages-and-regular-packages) for now) in a post-processing step we could look at 'module2's symbol table and add it's surface area symbols into 'my_module's surface area, we could treat them similar to simple relative imports.

We should be able to end up with something like:
```python
   "my_module.abs": {
        "type": SymbolType.RELATIVE_IMPORT,
        "data": {"shadows": "module2.abs},
    }
```

How far do we want to recurse?
If 'module2' has relative star imports the it really gets fun, do we could keep recursing into the abyss and bubble up all symbols into 'my_module's surface area?

In any case, I think our runs shouldn't fail if there is no "shadows" on a star import, our data model doe snot define "shadows" for star imports.

**Comment by CJ-Wright** [comment]
The problem that I'm running into is that our code branch handling relative star imports has a call to `resolve_relative_import` which expects a `shadows` that is a string: https://github.com/symbol-management/symbol-exporter/blob/master/symbol_exporter/ast_package_symbol_extractor.py#L91

In this case we get a `None` which causes the system to balk.

**Comment by dacamo76** [comment]
Okay, I see what you mean. I'll take a look at it.

So the failure is only specifically for `from . import *`?
If so, what do we expect output of this to be?
Should we just skip over `from . import *` since it just exposes the module's own surface area.

A sample intermediate representation (before post processing) is:
```python
 'mm.~~RELATIVE~~.*': {'data': {'imports': [{'level': 1,
                                             'module': 'mm',
                                             'shadows': None}]},
                       'type': <SymbolType.RELATIVE_STAR_IMPORT: 10>}
```
There seems to be no useful information, so I think we should just skip it.

**Comment by dacamo76** [comment]
My previous example is with a `from . import *` in a standalone module, if there is a `__init__.py` and that exposes symbols and a module has `from . import *` then it will bring in all the symbols from the `__init__.py` file.

We should eventually handle this case, so I propose for now we add `{'shadows': '__init__'}` so in the next version we know what module to recurse into.
